### PR TITLE
Idea

### PR DESCRIPTION
**Pull request by RatoMarombeiro**
Can you guys add the whitty mod input system like this in the option: original input system whitty input system (Sorry for my bad english lol im learning How to speak english here in Brazil lol)

### CODE REVIEW

**Comment by ActualMandM** [comment]
poor luckydog7

**Comment by The-SGPT** [comment]
man why do people do this

**Comment by hdboye** [comment]
why

**Review by PrincessMtH — CHANGES_REQUESTED** [review]
please close this pull request

**Comment by TentaRJ** [comment]
> please close this pull request

I second this. Please close this PR.

**Comment by hdboye** [comment]
i agree with everyone sayin close this, i don't see the need for this. this is a mod to the game. ninjamuffin doesn't add mods to fnf that aren't made by himself.

**Comment by Injourn** [comment]
Adding to the pile: #644
#587 #521 #518 #513 #441 #266 #214 #193

This poor man's branch...

**Comment by ninjamuffin99** [comment]
messy PR !!! im scared so im going to close this!

**Pull request closed without merging**
