### PR TITLE
Modified Main Branch, Builds on Switch

### PR DESCRIPTION
**Pull request by BrandyBuizel**
Re-downloaded the most recent Funkin' push and edited the existing files(no lucky guitar in game files this time) to build successfully on switch. There are currently errors preventing the game from playing on the hardware, _but this is on the Nintendo SDK side of things to be worked out soon._

### CODE REVIEW

**Comment by ThePlank** [comment]
image
Yeah, This ain't gonna be merged when youre 277 commits behind.

**Comment by polybiusproxy** [comment]
image
what the-

**Comment by BrandyBuizel** [comment]
> image
> Yeah, This ain't gonna be merged when youre 277 commits behind.

Trust me it's fine, there are only 5 actual file conflicts; that's just what github thinks since I haven't pushed a commit since November-ish

**Comment by BrandyBuizel** [comment]
> image
> what the-

Funkin has approached the singularity

**Comment by ThePlank** [comment]
> > image
> > what the-
> 
> Funkin has approached the singularity

funkin has reached full capacity on github

**Pull request closed without merging**
