### PR TITLE
Unhardcore events like player 2 changes ecc.

### PR DESCRIPTION
**Pull request by LevitoDev**
So you can do in charting events named "Player 2 Change" ecc.

### CODE REVIEW

**Comment by KitOdin** [comment]
no making pull request from kade-engine to base game in the halls.

**Comment by prokube** [comment]
dude holy fuck S T O P

**Comment by Cheemsandfriends** [comment]
Holy fuck- STOP

**Comment by ThePlank** [comment]
fnf fans on github don't merge kade engine to master challenge (failed instantly)

**Comment by polybiusproxy** [comment]
based muffin

**Comment by prokube** [comment]
based muffin

**Pull request closed without merging**
