### PR TITLE
week 7??

### PR DESCRIPTION
**Pull request by fnffanspritemaker**
week 7

### CODE REVIEW

**Comment by PurpleButNotALight** [comment]
Please close this pr, this will be added in week 7

**Comment by VMGuy23** [comment]
Week 7 will be added in Week 7, yes

**Comment by Verwex** [comment]
Man this pull request needs to be removed. Not only would it already be applied when week 7 arrives without anyone's input because c'mon, but it also is so useless right now that I'm questioning why you'd go out and do it.

**Comment by nickpythonluajava** [comment]
no


close this

**Comment by Kiffolisk** [comment]
this pr does nothing at all

**Comment by FNFPlayer101** [comment]
legit useless

**Pull request closed without merging**
