### PR TITLE
Make link for downloads the latest version, not the Ludum Dare prototype

### PR DESCRIPTION
**Pull request by actuallyasmartname**

### CODE REVIEW

**Review by TentaRJ — COMMENTED** [review]
damn i really did mess this part up, huh?

**Comment by actuallyasmartname** [comment]
yeah

**Comment by ninjamuffin99** [comment]
bles bles bles

**Comment by sebby09559** [comment]
yooooo loooo

**Comment by fnffanspritemaker** [comment]
beep bap boop

**Comment by fnffanspritemaker** [comment]
_beep_

**Comment by aflacc** [comment]
> _beep_

hes saying a bunch of slurs i wouldn't repeat

**Comment by fnffanspritemaker** [comment]
beeeeep

**Comment by fnffanspritemaker** [comment]
how can i dowload fnf whit the new update?

**Comment by RobotoSkunk** [comment]
beep boop skedop beep

**Pull request merged**
