### PR TITLE
Please add WEEK.

### PR DESCRIPTION
**Pull request by Hallqueen14278**
am......

### CODE REVIEW

**Comment by napstaa967** [comment]
fnf fans on github don't merge kade engine to master challenge (failed instantly)

**Comment by KitOdin** [comment]
bitch why are you trying to commit a pull request from kade-engine into here.

**Comment by ThePlank** [comment]
The FitnessGram™ Pacer Test is a multistage aerobic capacity test that progressively gets more difficult as it continues. The 20 meter pacer test will begin in 30 seconds. Line up at the start. The running speed starts slowly, but gets faster each minute after you hear this signal. [beep] A single lap should be completed each time you hear this sound. [ding] Remember to run in a straight line, and run as long as possible. The second time you fail to complete a lap before the sound, your test is over. The test will begin on the word start. On your mark, get ready, start.

**Comment by AbnormalPoof** [comment]
man

@ninjamuffin99

**Pull request closed without merging**
