### PR TITLE
Update Project.xml

### PR DESCRIPTION
**Pull request by TentaRJ**
Puts license in exports/compiles of the code so mod makers don't get canceled :)

### CODE REVIEW

**Comment by aflacc** [comment]
project.xml is funny

**Review by HTV04 — CHANGES_REQUESTED** [review]
Couldn't it just be renamed to "LICENSE.txt"? lol

**Comment by TentaRJ** [comment]
> Couldn't it just be renamed to "LICENSE.txt"? lol

Couldn't the README just be named to "README"?

Come on it's funny.

**Comment by Steviegt6** [comment]
I'm more in favor of keeping "README" instead of a one-off joke about cancelling people purely because the License is actually important and people clearly don't bother to review the license themselves, so it's better to keep the amount of people that are going to attempt to discard it at a glance to a minimum.

**Review by Steviegt6 — APPROVED** [review]
Looks fine otherwise.

**Comment by HTV04** [comment]
> I'm more in favor of using "README"

@Steviegt6 There's already the "do NOT readme.txt" file, so "LICENSE.txt" would probably be best for this because it would draw the least attention to the file, as you suggested.

Letting mod makers know to include the license could be part of the source repo's README.

@TentaRJ "License so we don't get canceled" would not only appear in mods, but also official builds unless it was renamed before releases. It seems funny at first, but honestly it would just be pretty annoying.

**Comment by TentaRJ** [comment]
> > I'm more in favor of using "README"
> 
> 
> 
> @Steviegt6 There's already the "do NOT readme.txt" file, so "LICENSE.txt" would probably be best for this because it would draw the least attention to the file, as you suggested.
> 
> 
> 
> Letting mod makers know to include the license could be part of the build instructions of the source repo's README.
> 
> 
> 
> @TentaRJ "License so we don't get canceled" would not only appear in mods, but also official builds unless it was renamed before releases. It seems funny at first, but honestly it would just be pretty annoying.

Fine I changed it

**Review by HTV04 — APPROVED** [review]
Looks good. All I would recommend is that you add ".txt" to it so it's recognized as a text file.

**Comment by TentaRJ** [comment]
> Looks good. All I would recommend is that you add ".txt" to it so it's recognized as a text file.

all done

**Comment by nickpythonluajava** [comment]
great

**Comment by aflacc** [comment]
Since u guys are talking about the license what license do you think would fit what ninjamuffins going for

**Comment by HTV04** [comment]
Personally I think GPL v3 would be the best license for what ninjamuffin wants, but since that might be an issue for companies like Nintendo, others suggested MPL v2 as an option.

**Review by theblobscp — APPROVED** [review]
Looks good

**Review by Mar10Josh — APPROVED** [review]
Yes, maybe nobody wants to get canceled!

**Comment by Steviegt6** [comment]
> > I'm more in favor of using "README"
> 
> @Steviegt6 There's already the "do NOT readme.txt" file, so "LICENSE.txt" would probably be best for this because it would draw the least attention to the file, as you suggested.
> 
> Letting mod makers know to include the license could be part of the build instructions of the source repo's README.
> 
> @TentaRJ "License so we don't get canceled" would not only appear in mods, but also official builds unless it was renamed before releases. It seems funny at first, but honestly it would just be pretty annoying.

Meant LICENSE lmfao.

**Comment by TentaRJ** [comment]
> Meant LICENSE lmfao.

It's fine

**Comment by TentaRJ** [comment]
Closed this PR due to inactivity plus I don't think Ninjamuffin is gonna commit this smh

**Pull request closed without merging**
