### PR TITLE
Health Icons in charting state now match character in the song

### PR DESCRIPTION
**Pull request by CyndaquilDAC**
just a quick commit cuz this has been bugging me for a while. Ignore the "add gfchristmas" stuff, that was from another pr and i accidentally put it on master which i cloned for this branch

### CODE REVIEW

**Review by actuallyasmartname — APPROVED** [review]
🦀 nice

**Review by TentaRJ — APPROVED** [review]
👍

**Review by VoltrexMaster — APPROVED** [review]
:shipit:

**Comment by CyndaquilDAC** [comment]
OOPS IM STUPID AND FORGOT TO ADD PlayState AT THE BEGINNING OF THE PLAYER THING LOL FIXED

**Comment by CyndaquilDAC** [comment]
i swear if it still throws a null reference exception with all my fixes i will commit a war crime

**Comment by PrincessMtH** [comment]
this is already done in the private branch lol oops

**Comment by actuallyasmartname** [comment]
> this is already done in the private branch lol oops

oof

**Comment by PrincessMtH** [comment]
sorry to all those whose PRs will only be closed once the update comes out sadly i cannot merge or close them myself 😢

**Comment by CyndaquilDAC** [comment]
sad this one won't get merged but at least this nitpick that's been annoying me is fixed!

**Pull request closed without merging**
