### PR TITLE
Restore the old Blackout scene in Eggnog (Forget it)

### PR DESCRIPTION
**Pull request by Cheemsandfriends**
Ok so ninjamuffin updated the end songs so that it benefit the loading screens...
But he kinda destroyed the blackout at the end of eggnog in StoryMode
So I kinda Restored it...
kinda of.
(The audio like it's cut but at least it's something lol)

### CODE REVIEW

**Comment by ThePlank** [comment]
maybe instead of making it on a CurBeat (that may break a lot of mods if they dont use a song the same length and BPM as Eggnog) make it still be on SongEnd but with a FlxTimer that will wait to change the state.

**Comment by Cheemsandfriends** [comment]
@ThePlank Ok. You have actually gave me an idea.
when I find the solution and If I know how to edit my code again
I'll post it again

**Comment by Cheemsandfriends** [comment]
Maybe It doesn't need the last thing of eggnog but it worked for me lol

**Review by ThePlank — APPROVED** [review]
Works perfectly!

**Comment by PrincessMtH** [comment]
this is already in week7 update.

**Comment by Cheemsandfriends** [comment]
@PrincessMtH Didn't know lol

**Comment by Cheemsandfriends** [comment]
I'm gonna add a last thing LoL because i'm special and Because I can

**Comment by Cheemsandfriends** [comment]
Yeh Bye PR

**Pull request closed without merging**
