### PR TITLE
Useless comment

### PR DESCRIPTION
**Pull request by theblobscp**

### CODE REVIEW

**Review by Steviegt6 — CHANGES_REQUESTED** [review]
If it's useless, why bother with a PR?

**Review by PurpleButNotALight — CHANGES_REQUESTED** [review]
please close this pr

**Comment by nickpythonluajava** [comment]
i mean do what you want man but its just a comment

**Comment by ActualMandM** [comment]
this was actually a very useful comment

**Comment by theblobscp** [comment]
I can make the pr again

**Comment by ActualMandM** [comment]
no i meant the comment this PR removed was useful

**Comment by theblobscp** [comment]
I’m confused

**Pull request closed without merging**
