### PR TITLE
Create ...

### PR DESCRIPTION
**Pull request by josetzunun**

### CODE REVIEW

**Comment by ThePlank** [comment]
why

**Comment by ACrazyTown** [comment]
> why

probably a kid with access to the internet and 0 knowledge of using github

**Comment by MythsList** [comment]
Useless commit.

**Comment by Cheemsandfriends** [comment]
Wooooow...
WTF is this? XD

**Comment by hdboye** [comment]
This commit is one of the best commits i've seen, it drastically improves performance and makes the game basically run on any platform. Merge!

**Comment by josetzunun** [comment]
Sorry I accidentally made this

**Comment by nickpythonluajava** [comment]
wrong fork? :trollface:

**Comment by theblobscp** [comment]
When github noob

**Comment by josetzunun** [comment]
> When github noob

WDYM

**Comment by TheKitBoi** [comment]
> > When github noob
> 
> 
> 
> WDYM

Make things ur self instead of requesting them here

**Comment by TheKitBoi** [comment]
close this

**Comment by theblobscp** [comment]
> WDYM

The typical github noob makes useless prs, and actually thinks it's good. I admit, I use to be one. Anyway close it

**Pull request closed without merging**
