### PR TITLE
Readme Rewrite

### PR DESCRIPTION
**Pull request by regulad**
---
labels: documentation
---
Credited Bassetfilms
Reorganizaed build instructions & added more information
Added `.vsconfig` for easier Visual Studio setup

I really should've added all this back when I made #195...

### CODE REVIEW

**Comment by regulad** [comment]
Imagine leaving a TODO in a readme, cant be me

**Comment by AbnormalPoof** [comment]
god fucking damnit

**Comment by anysad** [comment]
well played you little shit

**Comment by regulad** [comment]
I thought I got an email for an interview but it was just this thread I last touched when I was a teenager. :p

**Pull request closed without merging**
