### PR TITLE
Controller Support

### PR DESCRIPTION
**Pull request by rockin-bopeebo**
I honestly don't know if I should put this here, but whatever.
In Friday Night Funkin', you can play with a controller, as you may know, however, there are no controls for controller in this.
I was wondering if you could possibly add this to the files, thank you, and have a good day.

### CODE REVIEW

**Comment by VoltrexMaster** [comment]
Too many conflicts 🤔

**Comment by TentaRJ** [comment]
Just use a joystick-to-key rebinder for controller support.

**Comment by Injourn** [comment]
It's almost a meme at this point to see luckydog7's master branch on someone else's pull request, this happens too often!😆#587 #521 #518 #513 #441#266 #214 #193

Seriously leave that poor branch alone!

**Comment by ninjamuffin99** [comment]
in the upcoming 0.2.8.0 update, there will be controller support, so I'll close this commit for now hehe thanks anyways hehe

**Pull request closed without merging**
