### PR TITLE
I pull

### PR DESCRIPTION
**Pull request by AD1340**
I pull

### CODE REVIEW

**Comment by MemeHoovy** [comment]
fuck off

**Comment by Ty1991twitter** [comment]
Bro made a pull request by accident and Memehoovy is bullying em 💀

**Comment by TheKitBoi** [comment]
We about to get sick of useless pr if it’s shit

**Comment by MemeHoovy** [comment]
> Bro made a pull request by accident and Memehoovy is bullying em 💀

it's fucking stupid

**Comment by Ty1991twitter** [comment]
It was an accident my guy literally dm'd me panicking and asking me how to delete it. (I fogor how to delete pr's)

**Comment by MemeHoovy** [comment]
> It was an accident my guy literally dm'd me panicking and asking me how to delete it. (I fogor how to delete pr's)

just tell him to hit the close button

**Comment by Ty1991twitter** [comment]
I'll tell em whenever he gets online 

> > It was an accident my guy literally dm'd me panicking and asking me how to delete it. (I fogor how to delete pr's)
> 
> just tell him to hit the close button

**Comment by AD1340** [comment]
sry lmao

**Pull request closed without merging**
