### PR TITLE
Please add DownScroll for mobile 

### PR DESCRIPTION
**Pull request by TankPain**
Please it will be helpful

### CODE REVIEW

**Comment by The-SGPT** [comment]
this poor mans branch

**Comment by TentaRJ** [comment]
Please close this PR

**Comment by VoltrexMaster** [comment]
My man opening the PRs with the exact same scuffed branch :suspect:

**Comment by hdboye** [comment]
So many people just openin pr's with other people's code

**Comment by actuallyasmartname** [comment]
close the fucking pr why are these pr's even existing

**Comment by Injourn** [comment]
Another one, #669 #644 #587 #521 #518 #513 #441 #266 #214 #193

**Comment by hdboye** [comment]
we need a way to block branches from getting added to pull requests

**Comment by Smokey555** [comment]
Oh boy

**Comment by PrincessMtH** [comment]
he actually did it god bless
image

**Comment by PurpleButNotALight** [comment]
best pr for this game ever 1!!111!!! (lol)

**Comment by PoketrainerMS** [comment]
there is no official mobile port wdym

**Comment by nickpythonluajava** [comment]
> there is no official mobile port wdym

kickstarter

**Comment by PoketrainerMS** [comment]
> > there is no official mobile port wdym
> 
> kickstarter

i posted that before i saw the kickstarter lol
and i think this pr might have been also but i might be wrong

**Comment by VMGuy23** [comment]
C O N F L I C T I N G   F I L E S

**Comment by nickpythonluajava** [comment]
too much commits

**Comment by VMGuy23** [comment]
> Another one, #669 #644 #587 #521 #518 #513 #441 #266 #214 #193

das a lot

**Comment by VMGuy23** [comment]
@ninjamuffin99 close this please

**Pull request closed without merging**
