### PR TITLE
Replace json files with their week 7 recharts (for real this time lmao) 

### PR DESCRIPTION
**Pull request by AbnormalPoof**
i replaced the song json files with their recharts done by mth (god bless you btw lol)
also i fixed a grammar error in the bug template lol

### CODE REVIEW

**Comment by ACrazyTown** [comment]
what is the point of this pr if the charts are gonna be included as soon as week 7 source comes out??

**Comment by AbnormalPoof** [comment]
better late than never lol

**Comment by ActualMandM** [comment]
like what acrazytown said, this is gonna be part of the week 7 source code once that eventually releases

**Comment by AbnormalPoof** [comment]
source code wont be out until a week or two, think of it like a head start ig

**Comment by ACrazyTown** [comment]
> source code wont be out until a week or two, think of it like a head start ig

yeah but??? its gonna be out EVENTUALLY, there's no need for a "head start", please close this, this is unneccesary

**Comment by Cheemsandfriends** [comment]
This is really unneccesary lol

**Comment by ThePlank** [comment]
The FitnessGram™ Pacer Test is a multistage aerobic capacity test that progressively gets more difficult as it continues. The 20 meter pacer test will begin in 30 seconds. Line up at the start. The running speed starts slowly, but gets faster each minute after you hear this signal. [beep] A single lap should be completed each time you hear this sound. [ding] Remember to run in a straight line, and run as long as possible. The second time you fail to complete a lap before the sound, your test is over. The test will begin on the word start. On your mark, get ready, start.

**Comment by Cheemsandfriends** [comment]
@ThePlank what

**Comment by ActualMandM** [comment]
> think of it like a head start ig
except the commit containing all of the recharts is gonna become public when the 0.2.8 source code releases

**Comment by AbnormalPoof** [comment]
okay

**Comment by MrClogsworthYT** [comment]
uh its been a month

**Pull request closed without merging**
