### PR TITLE
Optimize audio

### PR DESCRIPTION
**Pull request by erikdubbelboer**
Basically all browsers support AAC audio wrapped in an m4a container: https://caniuse.com/?search=aac

This saves us around 79MB of audio data which can make a huge difference for players on slow internet connections or with bandwidth limitations.

### CODE REVIEW

**Comment by ACardboardBox1** [comment]
useful prs!!?!? omg!!

**Review by trayfellow — APPROVED** [review]
hello is this imposter from among us

**Review by Steviegt6 — APPROVED** [review]
Everything looks good to me, though I haven't actually listened in to the new files myself.

**Review by polybiusproxy — APPROVED** [review]
A good way to optimize the game!
However, the problem are the big sprites.

**Comment by Steviegt6** [comment]
> 
> 
> A good way to optimize the game!
> However, the problem are the big sprites.

This will remain an issue until the end of time as far as I'm concerned.

**Comment by exurd** [comment]
Maybe there should be a setting to choose between the higher quality and lower quality versions so people can opt for whatever suits their bandwidth.

**Comment by erikdubbelboer** [comment]
> I think there should be more versions of those files with different bitrates. Then, you can choose between the higher quality and lower quality versions of those M4As and people can opt for whatever suits their bandwidth better.

The new audio is the same quality, its just a different file format which is much smaller. But I agree, it would be cool to have a throttle to use those with lower bitrate so its even smaller for people with slow connections that choose this.

**Comment by Cheemsandfriends** [comment]
Well...
It's true but In some browsers it has partial Support.
I suppose that it means that It's not 100% Sure that it could work properly.
It could save, Yes
Buut It's like playing the Russian Roulette on the audio on some browsers
Maybe in a few years it could be perfect but better not take risks if possible right now

**Comment by erikdubbelboer** [comment]
The only browser that doesn't support it is Opera Mini because that doesn't support anything and isn't in use anymore: https://caniuse.com/?search=aac

**Comment by Cheemsandfriends** [comment]
I didn't meant like no Support at all
I meant like the partial support of Firefox, Firefox for Android And the KaiOS 
As I say again. I suppose that it means that not have 100% to work right

**Comment by erikdubbelboer** [comment]
The partial support in Firefox is that it only supports the m4a wrapper like I encoded it. So it's supported by all browsers.

**Comment by Cheemsandfriends** [comment]
Oh
Then I guess It's fine
Except for Opera Mini but Opera Mini doesn't accept nothing xD

**Comment by ninjamuffin99** [comment]
intriguing, are u able to get it tested on mobile browsers?
reason i use MP3 because I KNOW it works on EVERY browser. ogg has issues with Mac / Safari browsers on iPhone at least.

**Review by AbnormalPoof — APPROVED** [review]
finally a useful pr lmao


i mean we all made useless prs once in our lives ig but still

**Comment by AbnormalPoof** [comment]
> not yet, but a mobile version is planned, and a mobile WEB version we especially want to run just as well as any other target.

maybe mobile web can use emscripten but ehhhh that requires opening another can of worms so maybe not

another idea i have is maybe changing the way audio is played

**Comment by ninjamuffin99** [comment]
mobile web version already is supported by HaxeFlixel, it'd just be HTML5, which is what the game runs on the web versions

**Comment by AbnormalPoof** [comment]
ah ok lol

**Comment by erikdubbelboer** [comment]
We deployed a version with AAC audio a while back on Poki. You can preview it here on mobile: https://poki.com/en/preview/23b224ec-5257-455c-bdde-af727d3bed06/be8a53e2-35d5-4a0f-985e-f13087d47c2b
The game loads for me on an iPhone and I hear the menu music (so AAC works), you just can't continue as you can't press enter 😄 The AAC version of the game has a higher conversion to play, so it works well.

**Comment by ninjamuffin99** [comment]
ew wait i hate poki u guys stole the game and put a billion ads on your site so slimy ew ew ew im closing this now sorry gamer!

**Comment by AbnormalPoof** [comment]
they removed the fucking donate button bruh

**Comment by trayfellow** [comment]
> they removed the fucking donate button bruh

thats suspicious

**Comment by erikdubbelboer** [comment]
@ninjamuffin99 Sorry I wasn't aware. I'm a developer at Poki and had nothing to do with putting the game on Poki. I just noticed an open source game on our platform and thought I could contribute some improvements.

About the donation link, I've asked around and from what I understand, our content team followed a policy in which they remove external links from games, which dates from a time where flash game publishers would trick users to click misleading "play" buttons to lure them to their sites. This is an outdated policy that absolutely shouldn't apply to donate links. I've passed on your feedback and requested for this policy to be changed. The donation link was put back this morning.

I've also shared this thread with one of the founders of Poki, asking him to resolve this situation in a way that's fair. I think he already contacted you.

**Pull request closed without merging**
