### PR TITLE
Update to a proper license (The Unlicense)

### PR DESCRIPTION
**Pull request by lolBoi9696**
This pull request changes the license to a modified version of
The Unlicense which i have added 1 line to it saying you must open source your mods
I think since this is a free open source game and mostly your accepting any thing people make with it this will
Be the perfect license for Friday Night Funkin change anything you need :)

### CODE REVIEW

**Comment by VMGuy23** [comment]
Hi, please correct your spelling mistakes.

**Comment by nickpythonluajava** [comment]
i think this would be a perfect license because it allows people to do anything with no conditions

**Comment by lolBoi9696** [comment]
> Hi, please correct your spelling mistakes.
> You can directly copy from below:
> 
> ```
> This is free and unencumbered software released into the public domain.
> 
> Anyone is free to copy, modify, publish, use, compile, sell, or
> distribute this software, either in source code form or as a compiled
> binary, for any purpose, commercial or non-commercial, and by any
> means.
> 
> In jurisdictions that recognize copyright laws, the author or authors
> of this software dedicate any and all copyright interest in the
> software to the public domain. We make this dedication for the benefit
> of the public at large and to the detriment of our heirs and
> successors. We intend this dedication to be an overt act of
> relinquishment in perpetuity of all present and future rights to this
> software under copyright law.
> 
> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
> EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
> MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
> IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
> OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
> ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
> OTHER DEALINGS IN THE SOFTWARE.
> 
> For more information, please refer to <http://unlicense.org/>
> ```

spelling mistakes? i changed it a little thats why

**Review by polybiusproxy — APPROVED** [review]
poggers

**Comment by aflacc** [comment]
personally i like the current license more its much more comedic

**Comment by ACrazyTown** [comment]
> personally i like the current license more its much more comedic

while your statement is true
someone could literally sue ninjamuffin if their game runs under 60fps

**Comment by aflacc** [comment]
> > personally i like the current license more its much more comedic
> 
> while your statement is true
> someone could literally sue ninjamuffin if their game runs under 60fps

oh good idea 

me omw (on my way) to sue ninjamuffin because my games running at 59 fps

**Comment by VMGuy23** [comment]
> > Hi, please correct your spelling mistakes.
> > You can directly copy from below:
> > ```
> > This is free and unencumbered software released into the public domain.
> > 
> > Anyone is free to copy, modify, publish, use, compile, sell, or
> > distribute this software, either in source code form or as a compiled
> > binary, for any purpose, commercial or non-commercial, and by any
> > means.
> > 
> > In jurisdictions that recognize copyright laws, the author or authors
> > of this software dedicate any and all copyright interest in the
> > software to the public domain. We make this dedication for the benefit
> > of the public at large and to the detriment of our heirs and
> > successors. We intend this dedication to be an overt act of
> > relinquishment in perpetuity of all present and future rights to this
> > software under copyright law.
> > 
> > THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
> > EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
> > MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
> > IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
> > OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
> > ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
> > OTHER DEALINGS IN THE SOFTWARE.
> > 
> > For more information, please refer to <http://unlicense.org/>
> > ```
> 
> spelling mistakes? i changed it a little thats why

There are missed spaces and stuff

**Comment by lolBoi9696** [comment]
> > > Hi, please correct your spelling mistakes.
> > > You can directly copy from below:
> > > ```
> > > This is free and unencumbered software released into the public domain.
> > > 
> > > Anyone is free to copy, modify, publish, use, compile, sell, or
> > > distribute this software, either in source code form or as a compiled
> > > binary, for any purpose, commercial or non-commercial, and by any
> > > means.
> > > 
> > > In jurisdictions that recognize copyright laws, the author or authors
> > > of this software dedicate any and all copyright interest in the
> > > software to the public domain. We make this dedication for the benefit
> > > of the public at large and to the detriment of our heirs and
> > > successors. We intend this dedication to be an overt act of
> > > relinquishment in perpetuity of all present and future rights to this
> > > software under copyright law.
> > > 
> > > THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
> > > EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
> > > MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
> > > IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
> > > OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
> > > ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
> > > OTHER DEALINGS IN THE SOFTWARE.
> > > 
> > > For more information, please refer to <http://unlicense.org/>
> > > ```
> > 
> > 
> > spelling mistakes? i changed it a little thats why
> 
> There are missed spaces and stuff

i didnt see any missed spaces and stuff??

**Comment by aflacc** [comment]
oh ninja mad

**Comment by ninjamuffin99** [comment]
no i just dont think unlicense will be applicable for funkin

**Comment by nickpythonluajava** [comment]
> no i just dont think unlicense will be applicable for funkin

hahahaaa okay case closed

**Comment by aflacc** [comment]
> no i just dont think unlicense will be applicable for funkin

it will never be funkin

**Pull request closed without merging**
