### PR TITLE
Make the website look better

### PR DESCRIPTION
**Pull request by theblobscp**
I added the bootstrap, and touched up the css code to make the format look less... FUNKY

### CODE REVIEW

**Comment by theblobscp** [comment]
I just realized that this pull request is the 69th open one.

**Comment by ThePlank** [comment]
good pr but ninjamuffin said that hes learning web design and dosent what anyone to help him (i think thats how he said it but yea)

**Comment by theblobscp** [comment]
Oh

**Comment by prokube** [comment]
yo, i wanna see this. set up GitHub Pages because this might be cool

**Comment by theblobscp** [comment]
On my repo?

**Comment by theblobscp** [comment]
> yo, i wanna see this. set up GitHub Pages because this might be cool

I have something similar going on at https://funkindocs.vercel.app/

**Comment by ninjamuffin99** [comment]
i wanna make the website, lol sorry!
moreso like my own lil exercise in HTML and CSS type stuff, and its not some major code thing. like a little side project

**Comment by theblobscp** [comment]
Well have fun, also somewhat controversial opinion but sass/scss is the best library

**Pull request closed without merging**
