### PR TITLE
Better workflows.

### PR DESCRIPTION
**Pull request by Joalor64GH**
Now you won't have to be annoyed when the superlinter fails for no reason.
Also, WORKFLOWS!!!
Also, this is my first pull request (in this repo).

### CODE REVIEW

**Comment by theblobscp** [comment]
I did similar on #1718, do you wanna work together on one?

**Comment by s-zenmode** [comment]
super kewl

**Comment by s-zenmode** [comment]
ninjamuffin get on this or i'll slice your muffin in half

**Comment by s-zenmode** [comment]
that wasn't a threat

**Review by theblobscp — CHANGES_REQUESTED** [review]
Good, but why did you renamed the superlinter file? You should lowercase it lol

**Comment by Joalor64GH** [comment]
okay

**Review by theblobscp — APPROVED** [review]
Looks good. Not sure why you added the APIStuff file, but everything looks good.

**Review by theblobscp — APPROVED** [review]
Still works

**Comment by theblobscp** [comment]
Still think that was the best commit in all of FNF history.

**Comment by TheKitBoi** [comment]
> Still think that was the best commit in all of FNF history.

no

**Comment by ninjamuffin99** [comment]
i got workflows going all nice for the private branch, so gonna close this one but I appreciate it!!

**Pull request closed without merging**
