### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by TentaRJ**
Updated README.md to include the new Discord-RPC library in what to install.

### CODE REVIEW

**Comment by ninjamuffin99** [comment]
thnx gangsta heheh

**Comment by TentaRJ** [comment]
No problem.
Wanna know something funny? I have a compiling guide on gamebanana and people were panicking already on how to install discord_RPC. Guess I gotta go update my guide...

**Comment by fnffanspritemaker** [comment]
add spirit flash files and add senpai bg 1

**Comment by TentaRJ** [comment]
> add spirit flash files and add senpai bg 1

For the Spirit.xml, just change the txt file extension to XML

**Comment by fnffanspritemaker** [comment]
oh

**Comment by fnffanspritemaker** [comment]
> > add spirit flash files and add senpai bg 1
> 
> For the Spirit.xml, just change the txt file extension to XML

but it just go to the game files and search it and put on adobe animate to turn into a  apirit flash files??

**Pull request merged**
