### PR TITLE
Fix the spelling error in README (executible -> executable)

### PR DESCRIPTION
**Pull request by ACrazyTown**

### CODE REVIEW

**Comment by VMGuy23** [comment]
I think its a spelling error

**Review by actuallyasmartname — APPROVED** [review]
LGTM

**Comment by TentaRJ** [comment]
damnit thats my fault...

**Review by TentaRJ — APPROVED** [review]

**Comment by Th3SnowyOwl** [comment]
Tenta! Did you see me pull request?

**Comment by ninjamuffin99** [comment]
swag

**Pull request merged**
