### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by EpicGamerKermit**

### CODE REVIEW

**Comment by nickpythonluajava** [comment]
but..


why?

**Comment by ThePlank** [comment]
wy

**Comment by VMGuy23** [comment]
ninja muffin want to the website them self

**Comment by EpicGamerKermit** [comment]
oops i did this on accident

**Comment by EpicGamerKermit** [comment]
ignore

**Comment by EpicGamerKermit** [comment]
im closing this request

**Pull request closed without merging**
