### PR TITLE
folder

### PR DESCRIPTION
**Pull request by Diente111**
how do i make folders?

### CODE REVIEW

**Comment by cuckydev** [comment]
hacktober fest is over, my guy

**Comment by Cheemsandfriends** [comment]
Are you serious?

**Comment by ThePlank** [comment]
image

**Comment by AbnormalPoof** [comment]
@ninjamuffin99 I think you should close this pr just sayin lol



Anyway it's pretty complicated to make a new folder so just clone it make a new folder and push the changes via git

**Comment by MrClogsworthYT** [comment]
You monke just after writing the folder name type / and make a file 
Idk why but git doesn't allow you to make a folder without files like it deletes a directory if there are no files/folders inside it

**Comment by Lokitot** [comment]
I am currently crying so hard right now. This is seriously the most beautiful, well put together story ever. I can’t believe how magical it was 1:12. That part truly made me shed a tear. And especially at 6:34 that part was just so truly heart touching words can not describe the series of emotions I felt. I absolutely loved the climax it had insanely excellent detail. Oh and we can’t forget the conclusion. The conclusion was the greatest and saddest conclusion I have ever seen better than any of the books I have read. Thank you so much for creating this absolute masterpiece. This is essentially the most important masterpiece of film history. It is a tragedy that this, it can’t be called a film, but a transcendent emotional experience, will be inaccessible for most. It beautifully encapsulates the human struggle to its basics; suffering, pleasure, faith, despair. It connects with the characters within the viewers, individuals suppressed within our own subconscious. It stays vibrant, fresh, and revolutionizes the art of storytelling and filmmaking while making a damn of statement on what it means to be human. Entertaining, gripping, and simply exhilarating. This might be the most impactful piece of art I’ve come across in my life, and I’m definitely coming back to it in the near future to study it more deeply. this is an absolute masterpiece , I was brought to tears listening to this and seeing the bacon go whirly swirly in a circle countless times. it absolutely moved my soul , and I don't think I can ever be the same. this bacon has changed my entire mental state , I am now at peace with who I am and what I will be doing later in my life. i have forgiven all my enemies and now I am a man of a pacifist life. I will move on , gotta move on , as the song says. the bacon is so inspirational , it shares it vast wisdom with all of us , and we are all so lucky that it would bestow it's great words with us. we are all children on bacon. hail bacon. hail bacon. The spinning bacon, rotating in one direction with this music... This made me tear up. How could such a bacon do such a thing? I'm struck by awe by this masterpiece. Especially when the bacon spins, showing its lightly salt covered tan skin. I can hear the crunch just from here, and so as the beautiful sound of the bacon scraping the dark, smooth velvet floor.  The flavor, music and everything can be heard, tasted, seen and felt from a screen. You can really hear the breaths between the music artist, empathizing her love for this rotating bacon. Truly what I call modern art. This was the most legendary performance by any piece of bacon I have ever watched. The acting was top tier and very life changing. This is one of the greatest work from a piece of bacon I have ever seen especially on 57:42.I am currently crying so hard right now. This is seriously the most beautiful, well put together story ever. I can’t believe how magical it was at 1:12. That part truly made me shed a tear. And especially at 6:34 that part was just so truly heart touching words can not describe the series of emotions I felt. I absolutely loved the climax it had insanely excellent detail. Oh and we can’t forget the conclusion. The conclusion was the greatest and saddest conclusion I have ever seen better than any of the books I have read. Thank you so much for creating this absolute masterpiece. This is essentially the most important masterpiece of film history. It is a tragedy that this, it can’t be called a film, but a transcendent emotional experience, will be inaccessible for most. It beautifully encapsulates the human struggle to its basics; suffering, pleasure, faith, despair.  It connects with the characters within the viewers, individuals suppressed within our own subconscious. It stays vibrant, fresh, and revolutionizes the art of storytelling and filmmaking while making a damn of statement on what it means to be human. Entertaining, gripping, and simply exhilarating. This might be the most impactful piece of art I’ve come across in my life, and I’m definitely coming back to it in the near future to study it more deeply. this is an absolute masterpiece , I was brought to tears listening to this and seeing the bacon go whirly swirly in a circle countless times. Tt absolutely moved my soul , and i don't think I can ever be the same. this bacon has changed my entire mental state , I am now at peace with who I am and what I will be doing later in my life. i have forgiven all my enemies and now I am a man of a pacifist life. I will move on , gotta move on , as the song says. the bacon is so inspirational , it shares it vast wisdom with all of us , and we are all so lucky that it would bestow it's great words with us. we are all children on bacon. hail bacon. hail bacon. The spinning bacon, rotating in one direction with this music... This made me tear up. How could such a piece of bacon do such a thing? I'm struck by awe by this masterpiece. Especially when the bacon spins, showing its lightly salt covered tan skin. I can hear the crunch just from here, and so as the beautiful sound of the bacon scraping the dark, smooth velvet floor.  The flavor, music and everything can be heard, tasted, seen and felt from a screen. You can really hear the breaths between the music artist, empathizing her love for this rotating bacon. Truly what I call modern art. This was the most legendary performance by any bacon I have ever watched. The acting was top tier and very life changing. This is one of the greatest work from a bacon I have ever seen especially on 17:24. I am currently crying so hard right now. This is seriously the most beautiful, well put together story ever. I can’t believe how magical it was 1:12. That part truly made me shed a tear. And especially at 6:34 that part was just so truly heart touching words can not describe the series of emotions I felt. I absolutely loved the climax it had insanely excellent detail. Oh and we can’t forget the conclusion. The conclusion was the greatest and saddest conclusion I have ever seen better than any of the books I have read. Thank you so much for creating this absolute masterpiece. This is essentially the most important masterpiece of film history. It is a tragedy that this, it can’t be called a film, but a transcendent emotional experience, will be inaccessible for most. It beautifully encapsulates the human struggle to its basics; suffering, pleasure, faith, despair. The work put in to this is incredibly inspiring. The graphics, the animation, the music, so much thought was put into it. This has remined me that you can do anything you put your mind to. Not even mentioning the memories, this makes me feel like an infant again, just laying my eyes on this beautiful masterpiece gives me all the good feelings in life. I also understand what happiness is again from this. Not even to mention the most incredible part that is 2:10. Bacon spinning has changed my life for the better. It connects with the characters within the viewers, individuals suppressed within our own subconscious. It stays vibrant, fresh, and revolutionizes the art of storytelling and filmmaking while making a damn of statement on what it means to be human. Entertaining, gripping, and simply exhilarating. This might be the most impactful piece of art I’ve come across in my life, and I’m definitely coming back to it in the near future to study it more deeply. this is an absolute masterpiece , I was brought to tears listening to this and seeing the bacon go whirly swirly in a circle countless times. it absolutely moved my soul , and I don't think I can ever be the same. this bacon has changed my entire mental state , I am now at peace with who I am and what I will be doing later in my life. So much great graphic design, so much suspense, so much greatness in this one video. i have forgiven all my enemies and now I am a man of a pacifist life. I will move on , gotta move on , as the song says. the bacon is so inspirational , it shares it vast wisdom with all of us , and we are all so lucky that it would bestow it's great words with us. we are all children on bacon. hail bacon. hail bacon. The spinning bacon, rotating in one direction with this music... This made me tear up. How could such a bacon do such a thing? I'm struck by awe by this masterpiece. Especially when the bacon spins, showing its lightly salt covered tan skin. I can hear the crunch just from here, and so as the beautiful sound of the bacon scraping the dark, smooth velvet floor.  The flavor, music and everything can be heard, tasted, seen and felt from a screen. You can really hear the breaths between the music artist, empathizing her love for this rotating bacon. Truly what I call modern art. This was the most legendary performance by any bacon I have ever watched. The acting was top tier and very life changing. This is one of the greatest work from a piece of bacon I have ever seen especially on 57:42. I am crying. This has made me go through an emotional rollercoaster. I cried, beat off, and also watched a movie while watching this premiere. This has made me go through so much. I passed depression because of this. It really inspired me to become an outstanding young man. Thank you

**Pull request closed without merging**
