### PR TITLE
Add Kickstarter link to README

### PR DESCRIPTION
**Pull request by AugieDog08**

### CODE REVIEW

**Comment by Axmed119** [comment]
Okay

**Review by Steviegt6 — APPROVED** [review]
Suppose it makes sense.

**Comment by ninjamuffin99** [comment]
I prob shoulda added this, but oh well lolol we 4 days left now woops

**Comment by maska228** [comment]
> I prob shoulda added this, but oh well lolol we 4 days left now woops

Hi

**Pull request closed without merging**
