### PR TITLE
Un-hardcode icongrid icons

### PR DESCRIPTION
**Pull request by 4skinbruh**
Instead of having all icons in healthicon.hx, have them in a txt or json for easier icon adding/modding for beginners

### CODE REVIEW

**Comment by ThePlank** [comment]
why is this a pr

**Comment by VMGuy23** [comment]
image
@KadeDev did you just delete Funkin:master?

**Comment by VMGuy23** [comment]
Hi @4skinbruh - Please close this PR. We don't want all of KE in vanilla Funkin.

**Comment by aflacc** [comment]
NO MORE FUNKIN NOOOOOOOOOO

> image
> @KadeDev did you just delete Funkin:master?

**Comment by aflacc** [comment]
bruh did he just try to merge kade engine with the official....

am i seeing things or...

**Comment by 4skinbruh** [comment]
> bruh did he just try to merge kade engine with the official....
> 
> am i seeing things or...

i did a pull request in KE and idk what happened

**Pull request closed without merging**
