### PR TITLE
Loading gf-christmas as a character will no longer cause the game to crash

### PR DESCRIPTION
**Pull request by CyndaquilDAC**
adds gf-christmas to healthicon.hx so the game doesn't crash when you attempt to load her.

### CODE REVIEW

**Comment by CyndaquilDAC** [comment]
(sorry for it using my org, i have a kade engine fork on this account so i couldn't refork the og. github why havent you allowed multiple forks when one of the forks is a fork of a fork AHHHHHHHHHHHHHHHHHHHHHHHHH that would be so useful)

**Comment by aflacc** [comment]
I mean, we could just remove her. She doesn't exactly have a purpose outside of decoration

**Comment by VMGuy23** [comment]
> I mean, we could just remove her. She doesn't exactly have a purpose outside of decoration

Yeah true but the decoration counts. Preventing game crashes when people try to experiment is a good thing

**Comment by CyndaquilDAC** [comment]
has been fixed in the week 7 release

**Pull request closed without merging**
