### PR TITLE
Making README.md look pretty

### PR DESCRIPTION
**Pull request by TentaRJ**
This is an extension of #633 because I wanted to try to squash the commits into one. If this PR does get pushed, please squash it.

Anyway, what does this do?

README.md now looks pretty :)

I've added icons for the creators, the logo of the game, and the logo for Haxe and Lime. I've also made this README.md much prettier to read and more understandable while still retaining all of the information that was pushed into this file.

I've done a lot with this .w.

### CODE REVIEW

**Comment by TentaRJ** [comment]
### Yeah uhhh... please squish this if you are going to commit it...

**Comment by TentaRJ** [comment]
@ninjamuffin99 
👉 👈 
hi...

**Comment by OPNA2608** [comment]
I'm confused by the decision to make another PR. Why don't you squash the commits yourself?

**Comment by OPNA2608** [comment]
Oh yikes, I see why you may have trouble with this. For the future, you should always make a new branch before committing changes, and if you want to update your branch to get the changes from another branch/remote then it's cleaner to [`git rebase`](https://git-scm.com/book/en/v2/Git-Branching-Rebasing) it instead of merging them.

(I think) I've untangled and squashed your branch's commits without any losses in https://github.com/OPNA2608/Funkin/commit/fee4cc11f90fa203ed436e866c6dcb7df427f64a, give it a quick look if you want. Feel free to copy the branch to your repo, or retarget the PR to merge my branch into this repo instead, or re-commit it so you're the proper author, or whatever else you want.

**Comment by TentaRJ** [comment]
> Oh yikes, I see why you may have trouble with this. For the future, you should always make a new branch before committing changes, and if you want to update your branch to get the changes from another branch/remote then it's cleaner to [`git rebase`](https://git-scm.com/book/en/v2/Git-Branching-Rebasing) it instead of merging them.
> 
> 
> 
> (I think) I've untangled and squashed your branch's commits without any losses in https://github.com/OPNA2608/Funkin/commit/fee4cc11f90fa203ed436e866c6dcb7df427f64a, give it a quick look if you want. Feel free to copy the branch to your repo, or retarget the PR to merge my branch into this repo instead, or re-commit it so you're the proper author, or whatever else you want.

Yeah I just didn't know in advance, so that's my bad. Whoops...

**Comment by Th3SnowyOwl** [comment]
I suggest instead of just putting the authors horizontal, use a table like this change request I made.

**Pull request closed without merging**
