### PR TITLE
Remove the extra haxeflixel link

### PR DESCRIPTION
**Pull request by theblobscp**
If you install Flixel using haxelib as the instructions say, you don't need to go to the link to install it again

### CODE REVIEW

**Comment by AbnormalPoof** [comment]
Unnecessary since lime needs to be installed via the link, and the repo assumes you did that

**Comment by theblobscp** [comment]
Actually, you can install lime using haxelib too, so there's no need for the extra link. I'm gonna add that too now.

**Review by AbnormalPoof — CHANGES_REQUESTED** [review]
maybe add `haxelib run lime setup flixel` and `haxelib run lime setup` below `So for each of those type` `haxelib install [library]` `so shit like` `haxelib install newgrounds`

**Comment by AbnormalPoof** [comment]
and maybe add openfl to the dependency list while you're at it lol

**Comment by theblobscp** [comment]
When did I do this

**Pull request closed without merging**
