### PR TITLE
README corrections

### PR DESCRIPTION
**Pull request by itskwartz**

### CODE REVIEW

**Comment by TentaRJ** [comment]
👎

**Comment by foxsouns** [comment]
Why?

**Comment by ACrazyTown** [comment]
I think @DespawnedDiamond found out that not all those things are needed (with confirmation from ninjamuffin) but it would be better to test it out completely. I think he said that MSCV might be the only thing needed but he also said he's gonna try playing around with it to see what's actually needed. I'd say to wait for either ninjamuffin to change it himself or someone to fully test it and confirm it.

**Comment by itskwartz** [comment]
Oh, forgot to add a description, my bad

fixes spelling and directory names, as well as the individual components required to compile the game (which I've already tested myself)

**Comment by TentaRJ** [comment]
> Oh, forgot to add a description, my bad
> 
> fixes spelling and directory names, as well as the individual components required to compile the game (which I've already tested myself)

Alright. I changed my statement. 👍

**Review by hdboye — APPROVED** [review]
this works, merge ninjamuffin!!!!

**Comment by foxsouns** [comment]
Hell yeah! If I ever find myself needing to compile on Windows, this will be much more bearable.

**Review by Steviegt6 — APPROVED** [review]

**Comment by nickpythonluajava** [comment]
oh wait my free trial of Visual Studio Community 2019 expired

**Comment by nickpythonluajava** [comment]
> > oh wait my free trial of Visual Studio Community 2019 expired
> 
> 
> 
> Visual Studio Community is free. You probably installed Enterprise. (How is this relevant, by the way?)

i installed community

**Comment by foxsouns** [comment]
> now 4gb of crap?????
> 
> ferb i know what we're going to do today

~~install linux and only have to deal with \~300 mb of crap?~~

**Comment by actuallyasmartname** [comment]
conflict oh no

**Comment by VMGuy23** [comment]
What hapened here why is conflicst

**Comment by foxsouns** [comment]
@actuallyasmartname @VMGuy23 Ninja edited the readme along with that LICENSE commit.

**Comment by VMGuy23** [comment]
Ah....

**Comment by Steviegt6** [comment]
> > now 4gb of crap?????
> > ferb i know what we're going to do today
> 
> ~install linux and only have to deal with ~300 mb of crap?~

Install Linux and deal with Linux. /s

**Comment by VMGuy23** [comment]
> > > now 4gb of crap?????
> > > ferb i know what we're going to do today
> > 
> > 
> > ~install linux and only have to deal with ~300 mb of crap?~
> 
> Install Linux and deal with Linux. /s

Yeah Windows app support literally I found only one working app: Funkin.
Apart from that Linux great

**Review by polybiusproxy — APPROVED** [review]
merge this ninjamuffin or you are a poopy fart

**Comment by VMGuy23** [comment]
Conflict

**Comment by itskwartz** [comment]
Resolved conflict

**Comment by ninjamuffin99** [comment]
woops i think i just did that wit  29c8a26
so i will close this lol!

**Pull request closed without merging**
