### PR TITLE
.

### PR DESCRIPTION
**Pull request by ReylordFX**
a.

### CODE REVIEW

**Comment by polybiusproxy** [comment]
**PLEASE CLOSE THIS STUPID PULL REQUEST
CAN YOU STOP DOING PRs OF KADE ENGINE HERE, PLEASE??????
IF YOU DO NOT KNOW HOW TO PORT KE TO ANDROID, _THEN DONT OPEN A PR_**

this is not the first time **YOU** pull kade engine.
please, stop.

**Comment by ACrazyTown** [comment]
Close this PR, this is not the Kade Engine repo this is the vanilla FNF repo. Go to the KE repo instead because we can't help you here

**Comment by ReylordFX** [comment]
BECAUSE WHENEVER TRY TO PUT A NEW PULL REQUEST IT KEEPS TO NINJA'S GITHUB
IDK WHY

**Comment by ThePlank** [comment]
> BECAUSE WHENEVER TRY TO PUT A NEW PULL REQUEST IT KEEPS TO NINJA'S GITHUB
> IDK WHY

make a issue in kadengine and not a pull

**Comment by VoltrexMaster** [comment]
Doing an extensive amount of trolling with this kind of PRs again? :trollface:

**Comment by maska228** [comment]
nice

**Comment by Kappandrew** [comment]
If i had a nickel for every time someone tried to PR kade into the main, if have 10 cents, witch isnt  a lot but its odd it happened twice

**Comment by Kappandrew** [comment]
I mean id have about a dollar and 20 cents

**Comment by ACardboardBox1** [comment]
No. Just no.

**Comment by hdboye** [comment]
stop doing this you're not funny

**Comment by nickpythonluajava** [comment]
@KadeDev

**Comment by theblobscp** [comment]
I wanna see this dude trying to fix the 25+ merge conflicts.  It sounds like it will be entertaining.

**Comment by Kappandrew** [comment]
> I wanna see this dude trying to fix the 25+ merge conflicts.  It sounds like it will be entertaining.

 He's going to do 
_**absolutely nothing**_

**Comment by theblobscp** [comment]
Yeah lol

**Comment by arceuss** [comment]
no matter how hard youll try kade engine is not gonna be merged with fnf

**Comment by prokube** [comment]
Fucking no. We aren't merging Kade Engine, a **MOD**, into **VANILLA** Friday Night Funkin'.

Sincerely, Not a Child

**Comment by nickpythonluajava** [comment]
1.2k commits Jesus

**Comment by hdboye** [comment]
IS THERE A FUNCTION TO BLOCK THIS GUY FROM MAKING PULL REQUESTS HERE OR SUM THIS IS LIKE HIS 3RD PR

**Comment by theblobscp** [comment]
> IS THERE A FUNCTION TO BLOCK THIS GUY FROM MAKING PULL REQUESTS HERE OR SUM THIS IS LIKE HIS 3RD PR

Mabye if ninjamuffin blocks him? Idk, I'll look it up and find out

**Comment by theblobscp** [comment]
Ok so I looked it up. If ninjamuffins blocks him, this madness will end.

**Comment by theblobscp** [comment]
@ninjamuffin99  Friendly reminder to close this hellspawn and block this guy.

**Comment by ninjamuffin99** [comment]
sure just for u

**Comment by theblobscp** [comment]
Thanks muffin man

**Comment by ReylordFX** [comment]
> IS THERE A FUNCTION TO BLOCK THIS GUY FROM MAKING PULL REQUESTS HERE OR SUM THIS IS LIKE HIS 3RD PR

Bro i was dumb and didn't know that it was on ninja muffin's request

**Comment by theblobscp** [comment]
How did you forgot for two months. Come back when you have a better defense for being stupid.

**Pull request closed without merging**
