### PR TITLE
Accuracy Display

### PR DESCRIPTION
**Pull request by KadeDev**
This is a reopen of #249 

Adds an accuracy display and miss counter to the score of Friday night funkin.

It also makes the score easier to read on white backgrounds.

Screenshots:
image
image
image
image
image

### CODE REVIEW

**Comment by KadeDev** [comment]
bump

**Comment by KadeDev** [comment]
resolved some conflicts

**Comment by Smokey555** [comment]
Ignoring the best pull requests smh @ninjamuffin99

**Comment by ninjamuffin99** [comment]
cuz i dont want to do it this way

**Comment by nickpythonluajava** [comment]
adding_into_my_engine.mp4

**Pull request closed without merging**
