### PR TITLE
Make it actually show the creators names instead of just showing "PRESENT"

### PR DESCRIPTION
**Pull request by ACrazyTown**

### CODE REVIEW

**Comment by VMGuy23** [comment]
It's already in the NG version

**Comment by MythsList** [comment]
It shows but depending on your computer's performance it will skip that text.

**Comment by ACrazyTown** [comment]
> It shows but depending on your computer's performance it will skip that text.

I'm pretty sure it has to do with the music being played before all the intro assets were created, this PR just plays the music after everything's been made and loaded so the text should show up on mostly all devices

**Comment by cuckydev** [comment]
the actual reason this is an issue is because MusicBeatState sucks and skips steps, and if a step on a beat is skipped it also skips beats. stupid dum dumb

**Comment by PrincessMtH** [comment]
this is fixed in week7 update already through a more robust method but thank you!

**Pull request closed without merging**
