### PR TITLE
Miss counter + accuracy

### PR DESCRIPTION
**Pull request by KadeDev**
Adds a miss counter and accuracy to the score text object on the hud. 

Example:
image

### CODE REVIEW

**Comment by KadeDev** [comment]
Made the score text white and fixed an issue where it went above 100%.
image

**Comment by KadeDev** [comment]
Oh yeah @ninjamuffin99 you can 100% remove the ranking system if its not up to your liking, I just thought it was a neat idea!

**Comment by mesalikefortnite** [comment]
dope

**Comment by ThatOneCalculator** [comment]
Very nice addition!

**Comment by regulad** [comment]
> 
> 
> Made the score text outlined and fixed an issue where it went above 100%.
> image

guess this also closes #228, this is cool af

**Comment by Squiddu** [comment]
Is this just in-song at the moment or is there any other display in the menus of the rank/accuracy?

**Comment by regulad** [comment]
> 
> 
> Is this just in-song at the moment or is there any other display in the menus of the rank/accuracy?

It's just in-song, though a summary afterwards would also be pretty dang cool

**Comment by Squiddu** [comment]
Yeah.
I do think that should probably be its own pull request so this doesn't get too big.

**Comment by KadeDev** [comment]
> Yeah.
> I do think that should probably be its own pull request so this doesn't get too big.

yep

**Comment by regulad** [comment]
```
		// this is aids, I know it is aids. Please make this better, I hate looking at it.
		// I don't know what else I can do in this situation, maybe someone is smarter then me.
		// I want to use a switch case, but thats effor. I'm sorry for this mess.
```
fun comment

**Comment by KadeDev** [comment]
:)

**Comment by KadeDev** [comment]
Im going to reopen this hold on.

**Comment by izu-could** [comment]
How do i download?

**Comment by RHOMBOI** [comment]
This needs to happen man

**Comment by ninjamuffin99** [comment]
> 
> 
> This needs to happen man

the PR is closed dawg

**Comment by Kappandrew** [comment]
And thus, Kade Engine was born, and so was at least 15 ppl trying to merge kade with master

**Comment by nickpythonluajava** [comment]
> And thus, Kade Engine was born, and so was at least 15 ppl trying to merge kade with master

And thus, playstate gets frickin deleted

**Comment by Raltyro** [comment]
no way

**Pull request closed without merging**
