### PR TITLE
update to 4.2.4

### PR DESCRIPTION
**Pull request by nintendofan44**
there is no more problems with gits in this version so yea

### CODE REVIEW

**Comment by DotWith** [comment]
[dup](#1822)

**Comment by Cheemsandfriends** [comment]
> 
> 
> [dup](#1822)

what?

**Comment by DotWith** [comment]
> > [dup](#1822)
> 
> what?

duplicate

**Comment by nintendofan44** [comment]
> > > [dup](#1822)
> > 
> > 
> > what?
> 
> duplicate

of what?

**Comment by nintendofan44** [comment]
oh i think i know what u mean
this is for 4.2.4
the other one is for 4.2.3

**Comment by Cheemsandfriends** [comment]
> oh i think i know what u mean this is for 4.2.4 the other one is for 4.2.3

Oh, You meant that PR?
I didn't knew because the "dup" hyperlink redirected back to this PR lol

**Comment by Steviegt6** [comment]
> [dup](#1822)

In the future, just reply with #1822.

**Comment by DotWith** [comment]
> > [dup](#1822)
> 
> In the future, just reply with #1822.

spirit portrait 1

**Comment by nintendofan44** [comment]
oh lol

**Pull request closed without merging**
