### PR TITLE
Delete BeatBattle.hx

### PR DESCRIPTION
**Pull request by PurpleButNotALight**
Deletes blank "testing" file from the initial commit. I was questioning this file in #1018.

### CODE REVIEW

**Comment by PurpleButNotALight** [comment]
prob the most basic pr but its at least something lol

**Review by Steviegt6 — APPROVED** [review]
Completely useless file, as far as I know. Compiles fine without it.

**Review by theblobscp — APPROVED** [review]
There's nothing even there, no reason to keep it

**Comment by PurpleButNotALight** [comment]
it lliterally says 0 files (or lines idk) edited because i just deleted the file

**Comment by ninjamuffin99** [comment]
yolo

**Comment by maska228** [comment]
> yolo

Hi

**Comment by theblobscp** [comment]
> yolo
Hi muffin man

**Pull request merged**
