### PR TITLE
.

### PR DESCRIPTION
**Pull request by maska228**
a.

### CODE REVIEW

**Comment by ACrazyTown** [comment]
what

**Comment by maska228** [comment]
> what

my mom

**Comment by polybiusproxy** [comment]
> > what
> 
> my mom

this isnt gonna get merged

**Comment by prokube** [comment]
tfw you accidentally make a pr of your fork :trollface:

**Comment by theblobscp** [comment]
Look at this cringe

**Comment by hdboye** [comment]
what da hell

**Comment by theblobscp** [comment]
he deleted the fork, why is this stil open

**Comment by nickpythonluajava** [comment]
IM GONNA EURTEPSIRYJEI5TRJYOEIU5Y73U4HUTPE;SET'SPDEPKTNHRTNHONRO

**Comment by maska228** [comment]
> IM GONNA EURTEPSIRYJEI5TRJYOEIU5Y73U4HUTPE;SET'SPDEPKTNHRTNHONRO

lmfao

**Review by theblobscp — APPROVED** [review]
So good, they should make you the project leader

**Comment by ThePlank** [comment]
i like how his version of the game is just called Friday Night Funkin' Fork. There can be a milion forks, he isn't the only person with a fork.

**Comment by theblobscp** [comment]
Yeah, kinda sus

**Comment by maska228** [comment]
/-\

**Comment by theblobscp** [comment]
Finally

**Comment by polypoyo** [comment]
I liked the first commit

**Comment by maska228** [comment]
> I liked the first commit

yeah, it is a good commit
:+1: tbh

**Pull request closed without merging**
