### PR TITLE
Add the -easy and the -hard so you don't need to Rename

### PR DESCRIPTION
**Pull request by Cheemsandfriends**
Hello. So I wanted to make this since there is no way to save the things if you went from the difficulties. You can only rename if you want to make easy or hard.
this can be a solution to that problem lol

### CODE REVIEW

**Review by ThePlank — APPROVED** [review]
cool, but we need a difficulty dropdown now

**Comment by dum-du-m** [comment]
pls merge...

**Review by somefnfplayerlol — CHANGES_REQUESTED** [review]
add a difficulty dropdown to the charting menu

**Comment by ninjamuffin99** [comment]
the way different difficulty stuff is being handled is gonna be different in new update, so gon close dis for now since its kinda bein addressed hehehe

**Comment by Cheemsandfriends** [comment]
> 
> 
> the way different difficulty stuff is being handled is gonna be different in new update, so gon close dis for now since its kinda bein addressed hehehe

I'll definitely gonna remaster my thing when the thing comes out lol

**Pull request closed without merging**
