### PR TITLE
unseparate characters from their weeks

### PR DESCRIPTION
**Pull request by ActualMandM**
makes the game no longer crash if you use a character not from the song's specified week

this is a necessary change for custom songs (ex. [Dad Battle (In-Game Version)](https://youtu.be/2d0U8RHH3-E))

https://user-images.githubusercontent.com/15317421/109759423-d517f400-7ba1-11eb-92c3-96b3832af841.mp4

### CODE REVIEW

**Comment by hdboye** [comment]
The game never crashes when you change a character though
Also the only thing that you changed was where the character sprites were all located.
You can already change the characters without the need of this. It only changes where the character files are stored.

**Comment by ActualMandM** [comment]
This crashing issue only occurs on the current game code, not in the current game release.

**Comment by TentaRJ** [comment]
> This crashing issue only occurs on the current game code, not in the current game release.

no it doesn't

**Comment by ActualMandM** [comment]
https://user-images.githubusercontent.com/15317421/112906233-b58cc200-90a0-11eb-8c7b-df79f23ef6bc.mp4

**Comment by hdboye** [comment]
Just compiled the game with current code. You were right, it does crash. 
`Uncaught TypeError: Cannot read property 'name' of null`

**Comment by ActualMandM** [comment]
closing as i'm creating another pr that will involve this anyway

**Pull request closed without merging**
