### PR TITLE
Fixed memory usage issues

### PR DESCRIPTION
**Pull request by Naishaline**
Basically just tracks assets that are loaded in through add() then removes them when a new scene is loaded. Also some manual asset removal for a few areas that didn't really need all the tracking stuff.

Before this it was re-adding assets on every load, which caused memory usage to build up until the game wouldn't run. Now memory usage is relatively low and stays consistent during gameplay.

I created an issue earlier, but decided I could probably fix it myself and submit a pull request.

Overall not too much was actually added, so should be a pretty small change that makes a big difference. : )

### CODE REVIEW

**Comment by regulad** [comment]
Closes #268?

**Comment by Naishaline** [comment]
Also #58! Which I only noticed after making my pull request.

**Comment by B-Si** [comment]
GF assets

**Comment by nickpythonluajava** [comment]
> GF assets
> 
> 

????

**Comment by AbnormalPoof** [comment]
You saw nothing.

**Pull request closed without merging**
