### PR TITLE
README Rewrite

### PR DESCRIPTION
**Pull request by regulad**
---
labels: documentation
---

Rewrote most of the `README.md` and added a `.vsconfig` to make setting up your build environment easier. If this repo had wikis enabled I would have a wiki page instead, but it doesn't.

### CODE REVIEW

**Review by WaviestBalloon — APPROVED** [review]
image

**Comment by regulad** [comment]
man i sure do love when code reviewing means literally nothing on a repo with one maintainer

**Comment by WaviestBalloon** [comment]
Man I sure do love when comment

**Comment by AbnormalPoof** [comment]
you never saw anything.

**Pull request closed without merging**
