### PR TITLE
License

### PR DESCRIPTION
**Pull request by VMGuy23**
Probably a better one than before

### CODE REVIEW

**Comment by VMGuy23** [comment]
Don't do the snapcraft.yaml one

**Comment by Steviegt6** [comment]
Is this ironic?

**Comment by VMGuy23** [comment]
Well
it's better than the current one

**Comment by Steviegt6** [comment]
> Well
> it's better than the current one

That doesn't answer my question.
The current license is a placeholder.

**Comment by foxsouns** [comment]
what happened to the whole "no warranty" thing? why put that clause in?

**Comment by VMGuy23** [comment]
Where did I put that?

**Comment by ACrazyTown** [comment]
Wouldn't it be easier to just keep the current license and just not open source the switch port?

**Comment by VMGuy23** [comment]
> Wouldn't it be easier to just keep the current license and just not open source the switch port?

The current license allows people to sue ninjamuffin99 for performance issues.

**Comment by ACrazyTown** [comment]
> > Wouldn't it be easier to just keep the current license and just not open source the switch port?
> 
> The current license allows people to sue ninjamuffin99 for performance issues.

By current license I meant the Apache 2.0 license

**Comment by VMGuy23** [comment]
Oh. Well ninjamuffin wanted open-sourced mods.

**Comment by bonkmaykrQ** [comment]
What the fuck is with the suing part? Do you realize how fucked that part of the license is? It's so fucked, it's fucked six ways from Sunday.

Oh and, you're missing declaration of new definitions such as "software" etc which is necessary in order to prevent loopholes and shit.

The formatting is also just... Atrocious.

There is no effort made to actually describe the extent to which this license permits change or distribution, and what conditions must be met, which nearly invalidates any permissions given.

"Congratulations, you're a failure!" -The Spy

**Comment by VMGuy23** [comment]
Feel free to make your own, then.

> What the fuck is with the suing part? Do you realize how fucked that part of the license is? It's so fucked, it's fucked six ways from Sunday.
> 
> Oh and, you're missing declaration of new definitions such as "software" etc which is necessary in order to prevent loopholes and shit.
> 
> The formatting is also just... Atrocious.
> 
> There is no effort made to actually describe the extent to which this license permits change or distribution, and what conditions must be met, which nearly invalidates any permissions given.
> 
> "Congratulations, you're a failure!" -The Spy

**Comment by Steviegt6** [comment]
> 
> 
> Feel free to make your own, then.
> 
> > What the fuck is with the suing part? Do you realize how fucked that part of the license is? It's so fucked, it's fucked six ways from Sunday.
> > Oh and, you're missing declaration of new definitions such as "software" etc which is necessary in order to prevent loopholes and shit.
> > The formatting is also just... Atrocious.
> > There is no effort made to actually describe the extent to which this license permits change or distribution, and what conditions must be met, which nearly invalidates any permissions given.
> > "Congratulations, you're a failure!" -The Spy

Rebutting criticism by saying "make your own" is literally just another way of admitting defeat.

**Comment by prokube** [comment]
> Rebutting criticism by saying "make your own" is literally just another way of admitting defeat.

who says he isn't

**Comment by VMGuy23** [comment]
> > Rebutting criticism by saying "make your own" is literally just another way of admitting defeat.
> 
> who says he isn't

i kinda admit, it isnt very good. however, its not easy to make a license so feel free to make a new one if you think you can do better

**Pull request closed without merging**
