### PR TITLE
girlfriend cheering in tutorial

### PR DESCRIPTION
**Pull request by ActualMandM**
allows girlfriend to cheer in the tutorial by moving the if statement for tutorial outside of the one for bopeebo

additionally, make it work in conjunction with the tutorial audio itself

https://user-images.githubusercontent.com/15317421/109366979-ae785700-7849-11eb-8f09-194f0180c93b.mp4

### CODE REVIEW

**Comment by lolBoi9696** [comment]
Dude this is legit pointless lol

**Comment by KurtisCates** [comment]
> 
> 
> Dude this is legit pointless lol

Yea sure it's pointless but at least it's something.

**Comment by ActualMandM** [comment]
just putting technically unused code to use

**Comment by actuallyasmartname** [comment]
I mean, yeah when you say pointless it's pointless, but since it puts unused code to have a use i'm fine with it

**Comment by lolBoi9696** [comment]
i mean who would add this feature tho i mean it isnt a big change and it isnt Even a bug really and i dont think ninjamuffin is gonna accept it

**Comment by ninjamuffin99** [comment]
merging this because I don't like lolBoi9696's attitude

**Comment by TentaRJ** [comment]
> merging this because I don't like lolBoi9696's attitude

👏👏

**Comment by lolBoi9696** [comment]
> merging this because I don't like lolBoi9696's attitude

😢

**Comment by ninjamuffin99** [comment]
> > merging this because I don't like lolBoi9696's attitude
> 
> 😢

sorry bro, too much sass!!!

**Comment by lolBoi9696** [comment]
> > > merging this because I don't like lolBoi9696's attitude
> > 
> > 
> > 😢
> 
> sorry bro, too much sass!!!

y e s! s a s s is the best thing

**Comment by actuallyasmartname** [comment]
> merging this because I don't like lolBoi9696's attitude

hEhEhEhEhEhEhE

**Pull request merged**
