### PR TITLE
Add a mash button in options menu

### PR DESCRIPTION
**Pull request by OnsieRobYT**
I think it would be a good idea if you added a mash button in the options menu of 1.5.1 kade engine version

### CODE REVIEW

**Comment by VMGuy23** [comment]
Hi - You are attempting to merge 750 commits from Kade Engine. Please make your own fork, include the one piece of code, and submit another PR.
Also, please explain what you mean by a "mash button".

**Comment by Smokey555** [comment]
Wrong repository lol

**Comment by nickpythonluajava** [comment]
> Hi - You are attempting to merge 750 commits from Kade Engine. Please make your own fork, include the one piece of code, and submit another PR.
> 
> Also, please explain what you mean by a "mash button".

it probably means old input and new input toggle but idk

**Comment by nickpythonluajava** [comment]
also man this pr is confusing

**Comment by ActualMandM** [comment]
> Hi - You are attempting to merge 750 commits from Kade Engine. Please make your own fork, include the one piece of code, and submit another PR.
> Also, please explain what you mean by a "mash button".

they're directly merging kade engine into master lol

**Comment by ACardboardBox1** [comment]
oh my god

**Pull request closed without merging**
