### PR TITLE
cutsceneStuff folder

### PR DESCRIPTION
**Pull request by Sanscode1937**
I found cutsceneStuff on fnf 0.2.8 compiled code so idk

### CODE REVIEW

**Comment by AbnormalPoof** [comment]
Where did you even find these files?

**Comment by ACrazyTown** [comment]
> Where did you even find these files?

I think only a few images are in the 0.2.8 NG release, as for the text dialogue stuff I think they're fake

**Comment by Sanscode1937** [comment]
It doesn't exist so i make it lmao

**Comment by ThePlank** [comment]
ok, but why?

**Pull request closed without merging**
