### PR TITLE
vsync pog

### PR DESCRIPTION
**Pull request by itskwartz**
title says it all

### CODE REVIEW

**Comment by CaptainGame17** [comment]
doesnt fnf already have vsync (or an fps limit?)

**Comment by itskwartz** [comment]
There's an fps limit on the downloadable versions and vsync on web versions, this is just for people with high refresh rate monitors who want to use the downloadable versions (alternatively, they could replace Lib.application.window.displayMode.refreshRate with any integer they want if they want a specific framerate ig)

**Comment by ninjamuffin99** [comment]
INTRIGUING

**Comment by itskwartz** [comment]
There's also the framerate variable in Main but that only seems to be changeable outside of runtime & it makes the fps locked things even faster than the window.frameRate solution (no idea why)

**Comment by itskwartz** [comment]
And before anyone asks why I've added them to specifically those 3 states; pretty much every interactable state besides AnimationDebug and PauseSubstate extends MusicBeatState (so I don't need to copy and paste one extra line of code into every single state), and losing and regaining focus sets the framerate back to the variable in Main.

**Comment by itskwartz** [comment]
forgot to mention; enable vsync for both 'all targets' & 'windows specific' (this corrects the fps counter and it allows you to freely change your monitor refresh rate during runtime without having to restart)

**Comment by itskwartz** [comment]
yea this pr became a train wreck real quick so to clarify, vsync = true for 'all targets' & 'desktop specific' in Project.xml and the other code goes in MusicBeatState, MusicBeatSubstate and AnimationDebug

**Comment by itskwartz** [comment]
Ok i think i just figured out how vsync on web works so this pr may or may not get closed in ~24 hours just so i can make a fresh one that doesn't look this awful

i swear i know what i'm doing lmao

**Comment by itskwartz** [comment]
Actually, I'll just close it now and see what happens tomorrow

**Pull request closed without merging**
