### PR TITLE
remove daddy dearest from tutorial characters from story mode

### PR DESCRIPTION
**Pull request by actuallyasmartname**
smol patch

### CODE REVIEW

**Comment by CyndaquilDAC** [comment]
THANK YOU

**Review by CyndaquilDAC — APPROVED** [review]
LIKE GENUINELY THANK YOU THIS HAS BEEN BUGGING ME FOR FOREVERR

**Comment by actuallyasmartname** [comment]
> LIKE GENUINELY THANK YOU THIS HAS BEEN BUGGING ME FOR FOREVERR

haha

**Comment by aflacc** [comment]
Kades probs furious rn

**Comment by actuallyasmartname** [comment]
crap i deleted my fork

**Pull request closed without merging**
