### PR TITLE
Delete BOYFRIEND.png

### PR DESCRIPTION
**Pull request by luigigamer55**

### CODE REVIEW

**Comment by ElijahZAwesome** [comment]
why?

**Comment by lotusotho** [comment]
but why?
image

**Comment by ninjamuffin99** [comment]
OK MAYBE I WILL THINK ABOUT IT

**Comment by CorneliusCornbread** [comment]
luigi ballin

**Comment by ElijahZAwesome** [comment]
LUIGI_IS_BALLING

**Comment by gedehari** [comment]
the creator may accept this for the lolz

**Comment by WaviestBalloon** [comment]
image

**Comment by lotusotho** [comment]
image

**Comment by lotusotho** [comment]
103733104-90f7e100-4fae-11eb-97aa-bc0be5146819

**Comment by ninjamuffin99** [comment]
ok after thinking long and hard about it, I think im going to keep boyfrined.png, thanku for PR tho!!!!!! XDD

**Comment by Salladk-but-no-mo-flaged** [comment]
is bf gay?

i been asking but ppl think i was insulting

im not doing
so stop
get help
of hearing people

**Comment by Salladk-but-no-mo-flaged** [comment]
Luigi Ballin

**Pull request closed without merging**
