### PR TITLE
Better Note Hit System

### PR DESCRIPTION
**Pull request by 398utubzyt**
### Doubles and fast notes don't need frame-perfect key presses to be hit anymore.

Normally, double notes and notes close together would be really hard to hit because it thinks you missed it, otherwise known as ignoring your input. This new system should make the game feel more fair when playing faster mod songs like the B-Side levels, or playing maps with a lot of double notes like Monster.

### CODE REVIEW

**Comment by KurtisCates** [comment]
In my opinion this is tremendous sometimes it doesn't even resister your hit.

**Comment by 398utubzyt** [comment]
yeah, after playing other ddr-like games like quaver it can get a bit annoying after a while

**Comment by LordTet** [comment]
> Normally, double notes and notes close together would be really hard to hit because it thinks you missed it, otherwise known as ignoring your input. 

Is this the same bug as taps not registering if placed directly after holds? I wasn't aware it effective double taps, as well.

**Comment by 398utubzyt** [comment]
> Is this the same bug as taps not registering if placed directly after holds? I wasn't aware it effected double taps, as well.

It usually happens after a successful hit and immediately trying to hit another note, so I'm guessing it might be.

**Comment by aaa-321** [comment]
Thank you for this! For me I was having trouble with playing the mom week and Spookez. Now I can full combo them without having to worry about the game dropping inputs.

**Comment by The-SGPT** [comment]
I suffered on B-Sides Spookeez before I found this fix. Thanks!

**Comment by aaa-321** [comment]
Hey when you let notes go through they don't count as a miss or break your combo, but do lose health. Idk if that's intended or not

**Comment by 398utubzyt** [comment]
> Hey when you let notes go through they don't count as a miss or break your combo, but do lose health. Idk if that's intended or not

Yeah that usually happens if you hit a note at the same time, I'm working on a fix right now.

**Comment by 398utubzyt** [comment]
> Yeah that usually happens if you hit a note at the same time, I'm working on a fix right now.

Nevermind that happens whenever you miss, that shouldn't be happening.

**Comment by aflacc** [comment]
wait is this better or something yet

**Comment by 398utubzyt** [comment]
> wait is this better or something yet

yeah its a fixed version of the current input system

**Comment by aflacc** [comment]
> > wait is this better or something yet
> 
> yeah its a fixed version of the current input system

neato

**Comment by aflacc** [comment]
anyone wanna try and push this over to my [repo](https://github.com/aflacc/ProjectFNF)

**Comment by KurtisCates** [comment]
> anyone wanna try and push this over to my [repo](https://github.com/aflacc/ProjectFNF)

When I get home I will help you

**Comment by aflacc** [comment]
> > anyone wanna try and push this over to my [repo](https://github.com/aflacc/ProjectFNF)
> 
> When I get home I will help you

alright

**Comment by 398utubzyt** [comment]
so seems like the new update might have a new note hit system so this could be redundant at this point. i may be wrong though.

**Comment by KurtisCates** [comment]
> so seems like the new update might have a new note hit system so this could be redundant at this point. i may be wrong though.

I checked it is ;(

**Comment by aflacc** [comment]
just saying I tried using this and it doens't work that well. Half of the time (usually seems to happen after missing the first part of a hold note) it just doesn't actually count my hits and its really annoying.

**Comment by KurtisCates** [comment]
> just saying I tried using this and it doens't work that well. Half of the time (usually seems to happen after missing the first part of a hold note) it just doesn't actually count my hits and its really annoying.

Hey I know it's bad but you have to modify the code to make this better.  I made a fix for this enhancement ￼[My mod](https://gamebanana.com/gamefiles/20008)

**Comment by 398utubzyt** [comment]
week 7 update has new input

**Pull request closed without merging**
