### PR TITLE
Create Ninjastuff

### PR DESCRIPTION
**Pull request by Diente1112**

### CODE REVIEW

**Comment by VMGuy23** [comment]
what is this

**Review by ThePlank — APPROVED** [review]
Wow! How did ningamuffin99 not think of this!

**Comment by theblobscp** [comment]
I agree, this is so much work.

**Review by haya3218 — CHANGES_REQUESTED** [review]
needs more ninja

**Review by trayfellow — CHANGES_REQUESTED** [review]
also needs more muffins and 99's

**Comment by polybiusproxy** [comment]
yay, more useless pull requests!
you guys are wack! :D

**Comment by ACardboardBox1** [comment]
we need another admin on this repo there is WAY too many issues on here and useless pull requests.

**Comment by Steviegt6** [comment]
> 
> 
> we need another admin on this repo. there is WAY too many issues on here and useless pull requests.

I don't think it really matters all that much. I do wish that we could do some Spring Cleaning here but it doesn't impact development or anything. /shrug

**Comment by polybiusproxy** [comment]
> we need another admin on this repo. there is WAY too many issues on here and useless pull requests.

i agree
i wish i was an admin so i could close every pull requests tryin' to merge kade engine

**Review by JaredYoshi — COMMENTED** [review]
a

**Comment by theblobscp** [comment]
> we need another admin on this repo. there is WAY too many issues on here and useless pull requests.

yeah, but which of the people should it be? PhantomAracade? KawaiiSprite? Mabye they should make a twitter poll lol

**Comment by ACardboardBox1** [comment]
> 
> 
> > we need another admin on this repo. there is WAY too many issues on here and useless pull requests.
> 
> yeah, but which of the people should it be? PhantomAracade? KawaiiSprite? Mabye they should make a twitter poll lol

idk but it would be better if there was a more active admin or something. idk

**Comment by ACardboardBox1** [comment]
> 
> 
> > we need another admin on this repo. there is WAY too many issues on here and useless pull requests.
> 
> I don't think it really matters all that much. I do wish that we could do some Spring Cleaning here, but it doesn't impact development or anything. /shrug

yeah it wouldnt matter to much, but i just feel like if there was another admin on this repo to do some cleaning of the issues and pull requests it would be cool.

**Comment by theblobscp** [comment]
Make it KadeDev

**Pull request closed without merging**
