### PR TITLE
Smoke em out struggle for android

### PR DESCRIPTION
**Pull request by hatechara19**

### CODE REVIEW

**Comment by TheKitBoi** [comment]
Wrong pull request 
https://github.com/luckydog7/Funkin-android

**Comment by ThePlank** [comment]
h

**Comment by nickpythonluajava** [comment]
IM GOING TO KILL MYSELF GHIWPERHGW03URFHG350WHRG90W4GRU9R54UHGIG549

**Comment by ACardboardBox1** [comment]
i hate this branch <3

**Comment by VMGuy23** [comment]
> h

h

**Comment by TheKitBoi** [comment]
u better close that pull request right now

**Comment by Hendicted** [comment]
children shouldn't be allowed to use github

**Comment by polybiusproxy** [comment]
@ninjamuffin99

**Comment by KlavierGayming** [comment]
bruh

**Pull request closed without merging**
