### PR TITLE
feat(performance): Use switch statement

### PR DESCRIPTION
**Pull request by VoltrexMaster**
Use a `switch` statement instead of huge `if .. else if` chains.

### CODE REVIEW

**Review by TentaRJ — COMMENTED** [review]
Seems good! Have you tested this out to check to see if it works?

**Comment by VoltrexMaster** [comment]
> Seems good! Have you tested this out to check to see if it works?

yes

**Comment by TentaRJ** [comment]
> > Seems good! Have you tested this out to check to see if it works?
> 
> yes

Alright I'll try it on my build in a little bit to see if it works as well!

**Comment by lightbulblighter** [comment]
A switch statement rather than an if-else would result in zero to very minuscule performance improvements. We live in an era where such micro-optimizations will make a marginal improvement with the fast processors that we have. Nevertheless, this pull request sacrifices code readability. Switch statements are great for 1-2 line actions, not huge chunks of code. This would make it hard to see where a case ends and starts.

**Comment by VoltrexMaster** [comment]
> A switch statement rather than an if-else would result in zero to very minuscule performance improvements. We live in an era where such micro-optimizations will make a marginal improvement with the fast processors that we have. Nevertheless, this pull request sacrifices code readability. Switch statements are great for 1-2 line actions, not huge chunks of code. This would make it hard to see where a case ends and starts.

In the case of readability, it doesn't make mich difference between the huge block/chains of `if .. else if`s, it wouldn't make it harder to see where the braces start and end since it's almost the same case if huge chunks of `if .. else if` chains, although about the performance, the difference is not so little and miniscule since it just has to iterate through all of the conditions while also casting the string to lowercase all the time, sure it wouldn't make that big of a difference, but it's at least some performance boost, nothing bad at the very end, but I don't disagree with your point, just a little bit performance boost won't do any harm, this might be a huge performance boost in some cases but not entirely, so yea; not a bad point at least.

**Comment by lightbulblighter** [comment]
Usually when trying to give an application a "performance boost" or optimizing in general you will optimize the area where the bottleneck occurs. Switch statements are readable by only tabulation rather than braces. This area has no bottleneck and does not slow down the game at all. My point is that this seems like a useless pull request.

**Comment by VoltrexMaster** [comment]
> Usually when trying to give an application a "performance boost" or optimizing in general you will optimize the area where the bottleneck occurs. Switch statements are readable by only tabulation rather than braces. This area has no bottleneck and does not slow down the game at all. My point is that this seems like a useless pull request.

Performance boost doesn't exactly imply resolving bottlenecks in some areas of the code, it mostly means to just optimize the code as much as possible even if it means to sacrifice readability in anyway, I get what you're trying to say, this replacement of `if .. else if` chains with just a `switch` statement isn't exactly a big performance boost but I don't see anything wrong with even the slightest performance boost, but I get your point.

**Review by TentaRJ — APPROVED** [review]
These changes work as normal. The main improvement is readability and not having to use an if/else if string. I approve this. A minor change, but a good one to implement.

**Review by PrincessMtH — CHANGES_REQUESTED** [review]
most of the tabs seem to have accidentally been turned into double spaces.

**Comment by VoltrexMaster** [comment]
> most of the tabs seem to have accidentally been turned into double spaces.

Fixed 👍

**Comment by TentaRJ** [comment]
> most of the tabs seem to have accidentally been turned into double spaces.

Can't believe I didn't see that smh

**Comment by ninjamuffin99** [comment]
oops i actually did this in the private development repo already! I do appreciate it tho hehehe

**Comment by ninjamuffin99** [comment]
I'll merge for now anyways hehe

**Pull request merged**
