### PR TITLE
Fix github workflows

### PR DESCRIPTION
**Pull request by theblobscp**
Your workflow was completly broken, this pr fixes it and uses an actual linter.

### CODE REVIEW

**Review by ThePlank — APPROVED** [review]
WHY ISNT THIS JUST EMPTY FIES/FILES THAT HAVE NO PURPOSE AND KADE ENGINE PULLS :trollface:

**Comment by theblobscp** [comment]
I actually can't tell if you guys are trolling or think it's good

**Comment by ThePlank** [comment]
> I actually can't tell if you guys are trolling or think it's good

its good i just wanted to do some trolling :trollface:

**Comment by theblobscp** [comment]
Oh good I didn't want to ruin my 7 followers reputation

**Review by DotWith — APPROVED** [review]
Good I hate the errors it messes with my ocd

**Comment by s-zenmode** [comment]
ninjamuffo please

**Comment by theblobscp** [comment]
Does that mean you like it?

**Comment by DotWith** [comment]
> Does that mean you like it?

Yea, I phrased it incorrectly.

**Comment by theblobscp** [comment]
Not you  I meant @s-zenmode 
But thanks for enjoying it

**Comment by theblobscp** [comment]
Closing in favor of #2003.

**Pull request closed without merging**
