### PR TITLE
Cool boot up doodles(and also combo sprite + AnimationDebug implementation)

### PR DESCRIPTION
**Pull request by KitOdin**
is it just me or dose the boot up screen feel a bit, boring, I have come up with the best solution to spice up the boot screen for the game, there should be a 30% chance that a random doodle will replace the boot text, i have made 5 doodles as of now, this should be implemented to spice up the boot screen(not the haxelfixel logo).

edit : i made the AnimationDebug for EVERYONE 💯 🆒 
and also implemented the combo sprite so now its visible ☄️

### CODE REVIEW

**Comment by CyndaquilDAC** [comment]
1. you did not even program this in.
2. you aint the artist and its evident why

**Comment by Smokey555** [comment]
Tf is this

**Comment by KitOdin** [comment]
> Tf is this

i realized that theres a lack of any implementation for the combo text, and also noticed a animation debugger was in the game, but only in debug mode(meaning you cant access it in the base game without recompiling with the debug tag), so i made the debugger for everyone, and also re-added the combo sprite so that its visible

**Comment by omaemae** [comment]
children should not be allowed to use github

**Review by aflacc — CHANGES_REQUESTED** [review]
Just delete the whole thing

**Comment by PurpleButNotALight** [comment]
For first. The AnimationDebug state was made to make a accurate offset. You can only add offsets in the Characters.hx file and cannot be accesed by a release build. So the AnimationDebug inpementation is useless. For second. I don't know why the Combo sprite was removed (maybe aligment issue???) but i dont want this branch on my pc to test it. And for third. You didn't add the boot up sprites to replace the HaxeFlixel bootup. Don't allow kids (well, kids who know what theyre doing and can actually code) on Github.

**Comment by CyndaquilDAC** [comment]
Also btw I know kitodin through discord and iirc they’re 10 or 11. They CAN code, but not in haxe and it’s pretty evident

**Comment by aflacc** [comment]
> Also btw I know kitodin through discord and iirc they’re 10 or 11. They CAN code, but not in haxe and it’s pretty evident

they cant be on discord

**Comment by Steviegt6** [comment]
> Also btw I know kitodin through discord and iirc they’re 10 or 11. They CAN code, but not in haxe and it’s pretty evident

Then they're breaking the terms of service. I believe not reporting them is considered breaking the ToS as well. You should keep quite about people's ages.

**Comment by aflacc** [comment]
> > Also btw I know kitodin through discord and iirc they’re 10 or 11. They CAN code, but not in haxe and it’s pretty evident
> 
> Then they're breaking the terms of service. I believe not reporting them is considered breaking the ToS as well. You should keep quite about people's ages.

so ur encouraging them to try and let someone whos breaking the ToS keep using discord?

**Review by aflacc — CHANGES_REQUESTED** [review]
delete

**Review by actuallyasmartname — CHANGES_REQUESTED** [review]
dude what the f*ck is this art pls delete

**Pull request closed without merging**
