### PR TITLE
Much Better Github-Pages Site

### PR DESCRIPTION
**Pull request by regulad**
Didn't change anything contentful, but sure as hell made it a lot less janky.

### CODE REVIEW

**Comment by regulad** [comment]
Tested this locally with Jekyll, hence the `.gitignore` changes. Works like a charm, and now the icon works too!

**Comment by ninjamuffin99** [comment]
idk what jekyll is so im gonne close this lol get owned!!!

**Comment by KadeDev** [comment]
> idk what jekyll is so im gonne close this lol get owned!!!

10/10 comment would agree

**Comment by regulad** [comment]
> idk what jekyll is so im gonne close this lol get owned!!!

jekyll is what GitHub pages uses to build sites

**Comment by regulad** [comment]
also you still should fix the icon lol

**Pull request closed without merging**
